### ISSUE TITLE
Events from plotly

### ISSUE THREAD

**Issue by andrey-zakharov** [rwl/plotly#1]
Is it possible to bind to custom events from plotly?

**Comment by rwl** [comment]
It looks like the events are on the `div` element that you pass in.  You should be able to attach listeners there.

I guess we could add a `StreamController` for each type to make it more convenient.

**Comment by rwl** [comment]
It turns out that this was more complicated than I thought.  I added event streams in 70b901d6c9a2431955d40dca4ed32137f8574552 .  Unfortunately, the events that are passed to the handlers are the raw `JsObject` types.

Beware of the breaking change to the `Plot.selector` factory constructor.

Thank you for bringing this up.

**Comment by andrey-zakharov** [comment]
Its cool!
small note for Plot.selector, why not just replace it by ctor with document.querySelector inside?

But issue still here. there are more events in plotly and we need more generic way to retrieve it or add it hardcoded.

I'll make a pull request for it.
